### ISSUE TITLE
docs: translation of Simplified Chinese

### ISSUE THREAD

**Issue by unknwon** [flamego/flamego#78]
本工单为官网文档简体中文版本翻译的追踪工单，用于认领及追踪翻译进度。

所有的 PR 请发送到 https://github.com/flamego/flamego.dev 仓库的 `docs/zh-CN` 目录下。

- [x] README.md
- [x] starter-guide.md
- [x] core-concepts.md
- [x] core-services.md
- [x] custom-services.md
- [x] routing.md
- [x] faqs.md
- [x] middleware/*.md

认领页面请在下方评论。

### Setup

- https://v2.vuepress.vuejs.org/guide/i18n.html
